### ISSUE TITLE
Error compiling plugin

### ISSUE THREAD

**Issue by amjibaly** [cnavta/apache-camel-grails-plugin#1]
I created a brand new application with an empty route, but I get the following error when I run grails run-app.

$ java -version
java version "1.6.0_07"
Java(TM) SE Runtime Environment (build 1.6.0_07-b06-153)
Java HotSpot(TM) 64-Bit Server VM (build 1.6.0_07-b06-57, mixed mode)

$ grails run-app
Welcome to Grails 1.1.1 - http://grails.org/
Licensed under Apache Standard License 2.0
Grails home is set to: /Users/abdullah/grails-1.1.1

Base Directory: /Users/abdullah/NetBeansProjects/cameltest
Running script /Users/abdullah/grails-1.1.1/scripts/RunApp.groovy
Environment set to development
     [copy] Copied 5 empty directories to 3 empty directories under /Users/abdullah/.grails/1.1.1/projects/cameltest/resources
    [mkdir] Created dir: /Users/abdullah/NetBeansProjects/cameltest/web-app/plugins/camel-0.2
     [copy] Copying 27 files to /Users/abdullah/NetBeansProjects/cameltest/web-app/plugins/camel-0.2
  [groovyc] Compiling 8 source files to /Users/abdullah/.grails/1.1.1/projects/cameltest/classes
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed, Compile error during compilation with javac.
  [groovyc] /Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/ClosureProcessor.java:22: method does not override a method from its superclass
  [groovyc]     @Override
  [groovyc]          ^
  [groovyc] /Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/DefaultGrailsRouteClass.java:24: method does not override a method from its superclass
  [groovyc]     @Override
  [groovyc]          ^
  [groovyc] /Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:19: method does not override a method from its superclass
  [groovyc]     @Override
  [groovyc]          ^
  [groovyc] /Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:25: method does not override a method from its superclass
  [groovyc]     @Override
  [groovyc]          ^
  [groovyc] /Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:30: method does not override a method from its superclass
  [groovyc]     @Override
  [groovyc]          ^
  [groovyc] 5 errors
  [groovyc] 
  [groovyc] 
  [groovyc] 1 error
: Compilation Failed
    at org.codehaus.groovy.ant.Groovyc.compile(Groovyc.java:807)
    at org.codehaus.groovy.ant.Groovyc.execute(Groovyc.java:540)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at _GrailsCompile_groovy$_run_closure3_closure7.doCall(_GrailsCompile_groovy:102)
    at _GrailsCompile_groovy$_run_closure3_closure7.doCall(_GrailsCompile_groovy)
    at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:274)
    at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
    at _GrailsCompile_groovy$_run_closure3.doCall(_GrailsCompile_groovy:89)
    at _GrailsCompile_groovy$_run_closure2.doCall(_GrailsCompile_groovy:55)
    at _GrailsPackage_groovy$_run_closure2_closure9.doCall(_GrailsPackage_groovy:79)
    at _GrailsPackage_groovy$_run_closure2_closure9.doCall(_GrailsPackage_groovy)
    at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:274)
    at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
    at _GrailsPackage_groovy$_run_closure2.doCall(_GrailsPackage_groovy:78)
    at RunApp$_run_closure1.doCall(RunApp.groovy:28)
    at gant.Gant$_dispatch_closure4.doCall(Gant.groovy:324)
    at gant.Gant$_dispatch_closure6.doCall(Gant.groovy:334)
    at gant.Gant$_dispatch_closure6.doCall(Gant.groovy)
    at gant.Gant.withBuildListeners(Gant.groovy:344)
    at gant.Gant.this$2$withBuildListeners(Gant.groovy)
    at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
    at gant.Gant.dispatch(Gant.groovy:334)
    at gant.Gant.this$2$dispatch(Gant.groovy)
    at gant.Gant.invokeMethod(Gant.groovy)
    at gant.Gant.processTargets(Gant.groovy:495)
    at gant.Gant.processTargets(Gant.groovy:480)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed, Compile error during compilation with javac.
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/ClosureProcessor.java:22: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/DefaultGrailsRouteClass.java:24: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:19: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:25: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:30: method does not override a method from its superclass
    @Override
         ^
5 errors

1 error

```
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:296)
at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:143)
at org.codehaus.groovy.tools.javac.JavacJavaCompiler.addJavacError(JavacJavaCompiler.java:89)
at org.codehaus.groovy.tools.javac.JavacJavaCompiler.compile(JavacJavaCompiler.java:71)
at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit.gotoPhase(JavaAwareCompilationUnit.java:89)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:476)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:443)
at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:57)
at org.codehaus.groovy.tools.FileSystemCompiler.doCompilation(FileSystemCompiler.java:173)
at org.codehaus.groovy.ant.Groovyc.compile(Groovyc.java:792)
... 26 more
```

--- Nested Exception ---
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed, Compile error during compilation with javac.
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/ClosureProcessor.java:22: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/DefaultGrailsRouteClass.java:24: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:19: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:25: method does not override a method from its superclass
    @Override
         ^
/Users/abdullah/.grails/1.1.1/projects/cameltest/plugins/camel-0.2/src/java/org/ix/grails/plugins/camel/GrailsRouteBuilderFactoryBean.java:30: method does not override a method from its superclass
    @Override
         ^
5 errors

1 error

```
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:296)
at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:143)
at org.codehaus.groovy.tools.javac.JavacJavaCompiler.addJavacError(JavacJavaCompiler.java:89)
at org.codehaus.groovy.tools.javac.JavacJavaCompiler.compile(JavacJavaCompiler.java:71)
at org.codehaus.groovy.tools.javac.JavaAwareCompilationUnit.gotoPhase(JavaAwareCompilationUnit.java:89)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:476)
at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:443)
at org.codehaus.groovy.tools.FileSystemCompiler.compile(FileSystemCompiler.java:57)
at org.codehaus.groovy.tools.FileSystemCompiler.doCompilation(FileSystemCompiler.java:173)
at org.codehaus.groovy.ant.Groovyc.compile(Groovyc.java:792)
at org.codehaus.groovy.ant.Groovyc.execute(Groovyc.java:540)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
at org.apache.tools.ant.Task.perform(Task.java:348)
at _GrailsCompile_groovy$_run_closure3_closure7.doCall(_GrailsCompile_groovy:102)
at _GrailsCompile_groovy$_run_closure3_closure7.doCall(_GrailsCompile_groovy)
at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:274)
at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
at _GrailsCompile_groovy$_run_closure3.doCall(_GrailsCompile_groovy:89)
at _GrailsCompile_groovy$_run_closure2.doCall(_GrailsCompile_groovy:55)
at _GrailsPackage_groovy$_run_closure2_closure9.doCall(_GrailsPackage_groovy:79)
at _GrailsPackage_groovy$_run_closure2_closure9.doCall(_GrailsPackage_groovy)
at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:274)
at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
at _GrailsPackage_groovy$_run_closure2.doCall(_GrailsPackage_groovy:78)
at RunApp$_run_closure1.doCall(RunApp.groovy:28)
at gant.Gant$_dispatch_closure4.doCall(Gant.groovy:324)
at gant.Gant$_dispatch_closure6.doCall(Gant.groovy:334)
at gant.Gant$_dispatch_closure6.doCall(Gant.groovy)
at gant.Gant.withBuildListeners(Gant.groovy:344)
at gant.Gant.this$2$withBuildListeners(Gant.groovy)
at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
at gant.Gant.dispatch(Gant.groovy:334)
at gant.Gant.this$2$dispatch(Gant.groovy)
at gant.Gant.invokeMethod(Gant.groovy)
at gant.Gant.processTargets(Gant.groovy:495)
at gant.Gant.processTargets(Gant.groovy:480)
```

Compilation error: Compilation Failed

**Comment by kayflow** [comment]
In my case, I just removed all the @Overrides annotations, and got it work.
